// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBH4UW5zVUtv6Q5opMgfVXhnZXutnNB78E',
    appId: '1:866874537681:web:eba9a40d347b6973b9f7f0',
    messagingSenderId: '866874537681',
    projectId: 'glicare-39078',
    authDomain: 'glicare-39078.firebaseapp.com',
    databaseURL: 'https://glicare-39078-default-rtdb.firebaseio.com',
    storageBucket: 'glicare-39078.firebasestorage.app',
    measurementId: 'G-MKBCR7EHW2',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCtH4Ww5gGCvlOhDQd4jncy-6Upv9gWTYw',
    appId: '1:866874537681:android:8ea2f11390b3364ab9f7f0',
    messagingSenderId: '866874537681',
    projectId: 'glicare-39078',
    databaseURL: 'https://glicare-39078-default-rtdb.firebaseio.com',
    storageBucket: 'glicare-39078.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAQ2Sl78wDryRPZQRjdqpyWoykpvV4StGw',
    appId: '1:866874537681:ios:134b66f00c9dfb45b9f7f0',
    messagingSenderId: '866874537681',
    projectId: 'glicare-39078',
    storageBucket: 'glicare-39078.firebasestorage.app',
    iosBundleId: 'br.com.glicare.glicare',
  );
}